apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: personal-website-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: florianthom.io
    http:
      paths:
      - path: /
        backend:
          serviceName: personal-website-frontend-service
          servicePort: 3000
