apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: personal-website-frontend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-clusterissuer-personalwebsite-prod"
    # this option makes www.florianthom.io reachable from florianthom.io
    # and rewrites florianthom.io to www.florianthom.io
    # if the host were florianthom.io (and not www.florianthom.io like now) it would work with this option
    # also, but it would be vice-versa (www.florianthom.io would be rewritten to florianthom.io)
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - florianthom.io
    - www.florianthom.io
    # certificate can be created in 2 ways - 1. on your owm 2. with ingress-shim
    # has to match with certificate (if created on your owm)
    # here can be named custom when using ingress-shim (since it creates the certificate ressource on our behalf wit)
    secretName: letsencrypt-personal-website-secret
  rules:
  - host: www.florianthom.io
    http:
      paths:
      - path: /
        backend:
          serviceName: personal-website-frontend-service
          servicePort: 3000
      - path: /api
        backend:
          serviceName: personal-website-backend-service
          servicePort: 4000
      - path: /swagger
        backend:
          serviceName: personal-website-backend-service
          servicePort: 4000
